import type { Country, Gateway, PaymentMethodType, SortOption } from "./types"

export type IntegrationComplexity = "simple" | "moderate" | "complex"
export type FeeRange = "low" | "medium" | "high"

export const countries: Country[] = [
  { code: "sg", name: "Singapore", flag: "🇸🇬" },
  { code: "my", name: "Malaysia", flag: "🇲🇾" },
  { code: "id", name: "Indonesia", flag: "🇮🇩" },
  { code: "th", name: "Thailand", flag: "🇹🇭" },
  { code: "vn", name: "Vietnam", flag: "🇻🇳" },
  { code: "ph", name: "Philippines", flag: "🇵🇭" },
]

export const paymentMethodTypes: { value: PaymentMethodType; label: string; icon: string }[] = [
  { value: "credit_card", label: "Credit Card", icon: "💳" },
  { value: "e_wallet", label: "E-Wallet", icon: "📱" },
  { value: "bank_transfer", label: "Bank Transfer", icon: "🏦" },
  { value: "crypto", label: "Cryptocurrency", icon: "₿" },
  { value: "qr_code", label: "QR Code Payment", icon: "📲" },
]

export const integrationComplexities: { value: IntegrationComplexity; label: string; description: string }[] = [
  {
    value: "simple",
    label: "Simple",
    description:
      "Easy to integrate with minimal technical knowledge. Typically involves pre-built checkout pages or simple API calls. Integration time: 1-3 days.",
  },
  {
    value: "moderate",
    label: "Moderate",
    description:
      "Requires some development experience. Involves working with SDKs and moderate API complexity. Integration time: 1-2 weeks.",
  },
  {
    value: "complex",
    label: "Complex",
    description:
      "Requires significant technical expertise. Involves complex API integrations, custom workflows, and extensive testing. Integration time: 2+ weeks.",
  },
]

export const feeRanges: { value: FeeRange; label: string }[] = [
  { value: "low", label: "Low (< 2%)" },
  { value: "medium", label: "Medium (2-3%)" },
  { value: "high", label: "High (> 3%)" },
]

export const sortOptions: { value: SortOption; label: string }[] = [
  { value: "popularity", label: "Most Popular" },
  { value: "fee_low_to_high", label: "Lowest Fees First" },
  { value: "fee_high_to_low", label: "Highest Fees First" },
  { value: "complexity_simple_to_complex", label: "Easiest Integration First" },
  { value: "complexity_complex_to_simple", label: "Most Advanced First" },
]

export const comparisonCategories = [
  { id: "paymentMethods", label: "Payment Methods" },
  { id: "integrationTime", label: "Integration Time" },
  { id: "supportedCountries", label: "Supported Countries" },
  { id: "setupFee", label: "Setup Fee" },
  { id: "transactionFee", label: "Transaction Fee" },
  { id: "monthlyFee", label: "Monthly Fee" },
  { id: "features", label: "Key Features" },
]

export const paymentGateways: Gateway[] = [
  {
    id: "stripe",
    name: "Stripe",
    logo: "/images/stripe-logo.png",
    logoFallback: "💳",
    shortDescription: "Global payment processor with extensive API",
    countries: ["sg", "my", "th"],
    paymentMethodType: "credit_card",
    supportedPaymentMethods: ["credit_card", "bank_transfer"],
    integrationComplexity: "moderate",
    feeRange: "medium",
    features: ["Subscription billing", "Fraud detection", "Multi-currency", "Payment links"],
    fees: {
      setup: "Free",
      transaction: "2.9% + $0.30 per transaction",
      monthly: "No monthly fee",
      other: "1% for international cards",
    },
    popularity: 9,
    officialUrl: "https://stripe.com",
    apiDocUrl: "https://stripe.com/docs/api",
    feeStructureUrl: "https://stripe.com/pricing",
  },
  {
    id: "paypal",
    name: "PayPal",
    logo: "/images/paypal-logo.png",
    logoFallback: "🅿️",
    shortDescription: "International digital wallet and payment service",
    countries: ["sg", "my", "th", "ph", "vn", "id"],
    paymentMethodType: "e_wallet",
    supportedPaymentMethods: ["e_wallet", "credit_card", "bank_transfer"],
    integrationComplexity: "simple",
    feeRange: "medium",
    features: ["Buyer protection", "Express checkout", "Recurring payments", "International transfers"],
    fees: {
      setup: "Free",
      transaction: "3.4% + $0.30 per transaction",
      monthly: "No monthly fee",
      other: "1.5% for cross-border payments",
    },
    popularity: 10,
    officialUrl: "https://paypal.com",
    apiDocUrl: "https://developer.paypal.com/docs/api/overview/",
    feeStructureUrl: "https://www.paypal.com/us/webapps/mpp/merchant-fees",
  },
  {
    id: "grabpay",
    name: "GrabPay",
    logo: "/images/grabpay-logo.png",
    logoFallback: "🚕",
    shortDescription: "Southeast Asian mobile wallet from Grab",
    countries: ["sg", "my", "ph", "th", "vn", "id"],
    paymentMethodType: "e_wallet",
    supportedPaymentMethods: ["e_wallet", "qr_code"],
    integrationComplexity: "simple",
    feeRange: "low",
    features: ["QR payments", "Rewards program", "In-app payments", "Offline payments"],
    fees: {
      setup: "Free",
      transaction: "1.5% per transaction",
      monthly: "No monthly fee",
    },
    popularity: 8,
    officialUrl: "https://www.grab.com/sg/pay/",
    apiDocUrl: "https://developer.grab.com/docs/grabpay/",
    feeStructureUrl: "https://www.grab.com/sg/merchant/food/faq/",
  },
  {
    id: "gopay",
    name: "GoPay",
    logo: "/images/gopay-logo.png",
    logoFallback: "🛵",
    shortDescription: "Indonesia's leading digital wallet",
    countries: ["id"],
    paymentMethodType: "e_wallet",
    supportedPaymentMethods: ["e_wallet", "qr_code"],
    integrationComplexity: "simple",
    feeRange: "low",
    features: ["QR payments", "Bill payments", "Fund transfers", "In-app integration"],
    fees: {
      setup: "Free",
      transaction: "1.7% per transaction",
      monthly: "No monthly fee",
    },
    popularity: 7,
    officialUrl: "https://www.gojek.com/gopay/",
    apiDocUrl: "https://developer.gojek.com/docs/gopay/",
    feeStructureUrl: "https://www.gojek.com/gopay/merchant/",
  },
  {
    id: "dana",
    name: "DANA",
    logo: "/images/dana-logo.png",
    logoFallback: "💰",
    shortDescription: "Indonesian digital wallet and payment service",
    countries: ["id"],
    paymentMethodType: "e_wallet",
    supportedPaymentMethods: ["e_wallet", "qr_code"],
    integrationComplexity: "moderate",
    feeRange: "low",
    features: ["QR payments", "Bill payments", "Fund transfers", "Rewards program"],
    fees: {
      setup: "Free",
      transaction: "1.5% per transaction",
      monthly: "No monthly fee",
    },
    popularity: 6,
    officialUrl: "https://www.dana.id/",
    apiDocUrl: "https://developers.dana.id/",
    feeStructureUrl: "https://www.dana.id/business/pricing",
  },
  {
    id: "promptpay",
    name: "PromptPay",
    logo: "/images/promptpay-logo.png",
    logoFallback: "🇹🇭",
    shortDescription: "Thailand's national e-payment system",
    countries: ["th"],
    paymentMethodType: "bank_transfer",
    supportedPaymentMethods: ["bank_transfer", "qr_code"],
    integrationComplexity: "moderate",
    feeRange: "low",
    features: ["QR payments", "Bank account linking", "Fast transfers", "Government support"],
    fees: {
      setup: "Free",
      transaction: "1.0% per transaction",
      monthly: "No monthly fee",
    },
    popularity: 7,
    officialUrl: "https://www.bot.or.th/English/PaymentSystems/PSServices/PromptPay/",
    apiDocUrl: "https://developer.scb.co.th/promptpay/api-reference",
    feeStructureUrl: "https://www.bot.or.th/English/PaymentSystems/PSServices/PromptPay/Pages/default.aspx",
  },
  {
    id: "gcash",
    name: "GCash",
    logo: "/images/gcash-logo.png",
    logoFallback: "📱",
    shortDescription: "Leading mobile wallet in the Philippines",
    countries: ["ph"],
    paymentMethodType: "e_wallet",
    supportedPaymentMethods: ["e_wallet", "qr_code"],
    integrationComplexity: "moderate",
    feeRange: "medium",
    features: ["QR payments", "Bill payments", "Load money", "Send money"],
    fees: {
      setup: "Free",
      transaction: "2.0% per transaction",
      monthly: "No monthly fee",
    },
    popularity: 7,
    officialUrl: "https://www.gcash.com/",
    apiDocUrl: "https://www.gcash.com/business/developers",
    feeStructureUrl: "https://www.gcash.com/business/pricing",
  },
  {
    id: "momo",
    name: "MoMo",
    logo: "/images/momo-logo.png",
    logoFallback: "📲",
    shortDescription: "Vietnam's popular e-wallet and payment app",
    countries: ["vn"],
    paymentMethodType: "e_wallet",
    supportedPaymentMethods: ["e_wallet", "qr_code"],
    integrationComplexity: "moderate",
    feeRange: "medium",
    features: ["QR payments", "Bill payments", "Fund transfers", "Mobile top-up"],
    fees: {
      setup: "Free",
      transaction: "2.2% per transaction",
      monthly: "No monthly fee",
    },
    popularity: 6,
    officialUrl: "https://momo.vn/",
    apiDocUrl: "https://developers.momo.vn/",
    feeStructureUrl: "https://momo.vn/merchant/pricing",
  },
  {
    id: "boost",
    name: "Boost",
    logo: "/images/boost-logo.png",
    logoFallback: "🚀",
    shortDescription: "Malaysian e-wallet with lifestyle features",
    countries: ["my"],
    paymentMethodType: "e_wallet",
    supportedPaymentMethods: ["e_wallet", "qr_code"],
    integrationComplexity: "simple",
    feeRange: "low",
    features: ["QR payments", "Bill payments", "Rewards program", "Merchant solutions"],
    fees: {
      setup: "Free",
      transaction: "1.8% per transaction",
      monthly: "No monthly fee",
    },
    popularity: 5,
    officialUrl: "https://www.myboost.com.my/",
    apiDocUrl: "https://developer.myboost.com.my/docs",
    feeStructureUrl: "https://www.myboost.com.my/business/pricing",
  },
  {
    id: "dbs_paynow",
    name: "DBS PayNow",
    logo: "/images/dbs_paynow-logo.png",
    logoFallback: "🏦",
    shortDescription: "Singapore's instant fund transfer service",
    countries: ["sg"],
    paymentMethodType: "bank_transfer",
    supportedPaymentMethods: ["bank_transfer", "qr_code"],
    integrationComplexity: "simple",
    feeRange: "low",
    features: ["Instant transfers", "QR payments", "Mobile number linking", "Business payments"],
    fees: {
      setup: "Free",
      transaction: "0.8% per transaction",
      monthly: "No monthly fee",
    },
    popularity: 6,
    officialUrl: "https://www.dbs.com.sg/personal/deposits/pay-with-ease/paynow",
    apiDocUrl: "https://www.dbs.com.sg/corporate/solutions/cash-management/apis",
    feeStructureUrl: "https://www.dbs.com.sg/corporate/pricing/deposit-and-payment-services",
  },
  {
    id: "xendit",
    name: "Xendit",
    logo: "/images/xendit-logo.png",
    logoFallback: "✅",
    shortDescription: "Payment gateway for Indonesia and Philippines",
    countries: ["id", "ph"],
    paymentMethodType: "credit_card",
    supportedPaymentMethods: ["credit_card", "e_wallet", "bank_transfer", "qr_code"],
    integrationComplexity: "moderate",
    feeRange: "medium",
    features: ["Virtual accounts", "Disbursements", "Invoice system", "Recurring payments"],
    fees: {
      setup: "$99 one-time",
      transaction: "2.5% per transaction",
      monthly: "$29 per month",
    },
    popularity: 8,
    officialUrl: "https://www.xendit.co/",
    apiDocUrl: "https://developers.xendit.co/api-reference/",
    feeStructureUrl: "https://xendit.co/en/pricing/",
  },
  {
    id: "2c2p",
    name: "2C2P",
    logo: "/images/2c2p-logo.png",
    logoFallback: "🔄",
    shortDescription: "Payment processor across Southeast Asia",
    countries: ["sg", "my", "th", "ph", "vn", "id"],
    paymentMethodType: "credit_card",
    supportedPaymentMethods: ["credit_card", "e_wallet", "bank_transfer", "qr_code"],
    integrationComplexity: "complex",
    feeRange: "high",
    features: ["Alternative payments", "Fraud management", "Payment optimization", "Tokenization"],
    fees: {
      setup: "$199 one-time",
      transaction: "3.2% per transaction",
      monthly: "$49 per month",
      other: "Additional fees for premium features",
    },
    popularity: 7,
    officialUrl: "https://www.2c2p.com/",
    apiDocUrl: "https://developer.2c2p.com/docs",
    feeStructureUrl: "https://www.2c2p.com/pricing",
  },
]
